version: "1.0"

services:
  mysql:
    image: mysql:8
    container_name: shuttle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shuttle_system_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: shuttle-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:Marco2310%23@shuttle-mysql:3306/shuttle_system_db
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Marco2310#
      DB_NAME: shuttle_system_db
      JWT_SECRET: your_secrete_text
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: smarcoeam2310@gmail.com
      EMAIL_PASS: "ejbl wmse orby vmjx"
      EMAIL_FROM: "Shuttle System <smarcoeam2310@gmail.com>"

  frontend:
    build: ./frontend
    container_name: shuttle-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
